version: "3.7"

services:
  qdrant:
    image: qdrant/qdrant:latest
    restart: always
    container_name: qdrant
    ports:
      - 6333:6333
      - 6334:6334
    expose:
      - 6333
      - 6334
      - 6335
    volumes:
      - ./qdrant_data:/app/qdrant_data
  chat-bot:
    container_name: chat-bot
    image: chat-bot:1.0
    build:
      dockerfile: Dockerfile
      target: ""
    restart: always
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    volumes:
      - ./data:/app/data
      - ./models:/app/models
      - ./bm_storage:/app/bm_storage